#/** * @author MayilaiMuthu * @since 03-08-2023 **/

#Data Source Config

spring:
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://localhost/taxi
       username: root
       password: root
       
#Console Config

   h2:
    console:
      enabled: true  
      
#Console Config

   mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp 
      
#Security Config      

   security:
      user:
        name: admin
        password: admin        
       
#JPA Config

   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect
             
#Server Config             

server:
    port: 7072
    servlet:
      context-path: /api